buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Versão compatível com Java 17 e Gradle 8.x
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}